In [46]:
from sklearn.datasets import load_diabetes
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

In [47]:
diabetes = load_diabetes()

In [48]:
X = diabetes.data

In [49]:
y = diabetes.target

In [50]:
X

array([[ 0.03807591,  0.05068012,  0.06169621, ..., -0.00259226,
         0.01990749, -0.01764613],
       [-0.00188202, -0.04464164, -0.05147406, ..., -0.03949338,
        -0.06833155, -0.09220405],
       [ 0.08529891,  0.05068012,  0.04445121, ..., -0.00259226,
         0.00286131, -0.02593034],
       ...,
       [ 0.04170844,  0.05068012, -0.01590626, ..., -0.01107952,
        -0.04688253,  0.01549073],
       [-0.04547248, -0.04464164,  0.03906215, ...,  0.02655962,
         0.04452873, -0.02593034],
       [-0.04547248, -0.04464164, -0.0730303 , ..., -0.03949338,
        -0.00422151,  0.00306441]], shape=(442, 10))

In [51]:
y

array([151.,  75., 141., 206., 135.,  97., 138.,  63., 110., 310., 101.,
        69., 179., 185., 118., 171., 166., 144.,  97., 168.,  68.,  49.,
        68., 245., 184., 202., 137.,  85., 131., 283., 129.,  59., 341.,
        87.,  65., 102., 265., 276., 252.,  90., 100.,  55.,  61.,  92.,
       259.,  53., 190., 142.,  75., 142., 155., 225.,  59., 104., 182.,
       128.,  52.,  37., 170., 170.,  61., 144.,  52., 128.,  71., 163.,
       150.,  97., 160., 178.,  48., 270., 202., 111.,  85.,  42., 170.,
       200., 252., 113., 143.,  51.,  52., 210.,  65., 141.,  55., 134.,
        42., 111.,  98., 164.,  48.,  96.,  90., 162., 150., 279.,  92.,
        83., 128., 102., 302., 198.,  95.,  53., 134., 144., 232.,  81.,
       104.,  59., 246., 297., 258., 229., 275., 281., 179., 200., 200.,
       173., 180.,  84., 121., 161.,  99., 109., 115., 268., 274., 158.,
       107.,  83., 103., 272.,  85., 280., 336., 281., 118., 317., 235.,
        60., 174., 259., 178., 128.,  96., 126., 28

In [52]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size = 0.2, random_state = 3)

In [23]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)

In [25]:
X_test_scaled = scaler.transform(X_test)

In [53]:
X_train

array([[ 0.06713621, -0.04464164, -0.06117437, ..., -0.03949338,
        -0.0561531 , -0.05906719],
       [-0.05273755, -0.04464164, -0.01267283, ..., -0.00259226,
        -0.02712902, -0.05078298],
       [-0.05273755, -0.04464164, -0.05578531, ...,  0.03430886,
         0.13237579,  0.00306441],
       ...,
       [-0.01277963, -0.04464164,  0.06061839, ...,  0.03430886,
         0.07020738,  0.00720652],
       [-0.03457486,  0.05068012, -0.00081689, ...,  0.1081111 ,
         0.02671684,  0.07348023],
       [ 0.01991321,  0.05068012,  0.10480869, ..., -0.00259226,
         0.00370906,  0.04034337]], shape=(353, 10))

In [54]:
X_test

array([[-2.73097857e-02,  5.06801187e-02, -1.59062628e-02,
        -2.97703791e-02,  3.93485161e-03, -6.87580503e-04,
         4.12768238e-02, -3.94933829e-02, -2.36468631e-02,
         1.13486232e-02],
       [-2.36772472e-02, -4.46416365e-02,  5.95405824e-02,
        -4.00989321e-02, -4.28475456e-02, -4.35889198e-02,
         1.18237214e-02, -3.94933829e-02, -1.59988725e-02,
         4.03433716e-02],
       [ 1.62806757e-02,  5.06801187e-02, -4.60850009e-02,
         1.15438326e-02, -3.32158756e-02, -1.60318551e-02,
        -1.02661054e-02, -2.59226200e-03, -4.39837725e-02,
        -4.24987666e-02],
       [-1.88201653e-03,  5.06801187e-02, -3.31512560e-02,
        -1.83056854e-02,  3.14539088e-02,  4.28400557e-02,
        -1.39477432e-02,  1.99174217e-02,  1.02267162e-02,
         2.79170509e-02],
       [ 3.08108295e-02,  5.06801187e-02,  4.66068375e-02,
        -1.59989752e-02,  2.04462859e-02,  5.06687672e-02,
        -5.81273969e-02,  7.12099798e-02,  6.20673545e-03,
         7.

In [55]:
print(X_train_scaled,X_test_scaled)

[[ 1.40278971 -0.92622607 -1.2621765  ... -0.82078713 -1.15829597
  -1.21127255]
 [-1.09165348 -0.92622607 -0.26199324 ... -0.06034027 -0.56427787
  -1.04313286]
 [-1.09165348 -0.92622607 -1.15104503 ...  0.70010658  2.70020977
   0.04977506]
 ...
 [-0.26017242 -0.92622607  1.24939481 ...  0.70010658  1.42784689
   0.1338449 ]
 [-0.71370754  1.07965002 -0.01750399 ...  2.22100028  0.53775256
   1.47896235]
 [ 0.42013027  1.07965002  2.1606729  ... -0.06034027  0.06686636
   0.80640363]] [[-5.62529165e-01  1.07965002e+00 -3.28672122e-01 -6.23741724e-01
   8.75401775e-02 -3.78256925e-03  8.69959568e-01 -8.20787125e-01
  -4.93010624e-01  2.17914742e-01]
 [-4.86939978e-01 -9.26226072e-01  1.22716852e+00 -8.40693586e-01
  -9.14039623e-01 -9.18426727e-01  2.52060720e-01 -8.20787125e-01
  -3.36483871e-01  8.06403625e-01]
 [ 3.44541084e-01  1.07965002e+00 -9.51008376e-01  2.44065723e-01
  -7.07832017e-01 -3.30918071e-01 -2.11363416e-01 -6.03402729e-02
  -9.09233731e-01 -8.74993184e-01]
 [-3.34

In [56]:
lr = LinearRegression()

In [57]:
lr.fit(X_train_scale,y_train)

LinearRegression()

In [62]:
y_pred = lr.predict(X_test_scaled)

In [63]:
lr.coef_

array([ -0.05466153, -10.11664775,  26.20811647,  16.43443221,
       -43.82379675,  24.23206402,   8.23958416,  12.99880554,
        35.79685151,   3.45275567])

In [64]:
lr.intercept_

np.float64(153.56373937677054)

In [65]:
from sklearn.metrics import r2_score
r2_score(y_test,y_pred)

0.4161792211496943

In [77]:
import random
class MBGRegressor:

    def __init__(self, batch_size=10, learning_rate=0.01, epochs=100):
        self.intercept_ = 0
        self.coef_ = np.ones(X_train.shape[1])
        self.epochs = epochs
        self.lr = learning_rate
        self.batch_size = batch_size

    def fit(self,X_train,y_train):
        for i in range(self.epochs):
            for j in range(int(X_train.shape[0]/self.batch_size)):
                idx = random.sample(range(X_train.shape[0]), self.batch_size)
                y_hat = self.intercept_ + np.dot(X_train[idx], self.coef_)
                intercept_der = -2 * np.mean(y_train[idx] - y_hat)
                self.intercept_ = self.intercept_ - (self.lr * intercept_der)

                coef_der = -2 * np.dot((y_train[idx] - y_hat), X_train[idx])
                self.coef_ = self.coef_ - (self.lr * coef_der)

        print(self.intercept_, self.coef_)

    def predict(self, X_test):
        return np.dot(X_test, self.coef_) + self.intercept_

In [78]:
mbr = MBGRegressor()

In [79]:
mbr.fit(X_train_scaled,y_train)

153.80366506187212 [ -8.03178505 -17.21931492  22.48895957  19.74720117 -54.83672772
  20.59272346  19.80769937   6.13452613  42.6221705   -7.65782428]


In [81]:
y_pred_new = mbr.predict(X_test_scaled)

In [83]:
r2_score(y_test,y_pred)

0.4161792211496943